/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coaches` | `/coaches`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/inventory` | `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/membership` | `/membership`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/payment` | `/payment`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/plan` | `/plan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/report` | `/report`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/coaches` | `/coaches`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/inventory` | `/inventory`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/membership` | `/membership`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/payment` | `/payment`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/plan` | `/plan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/report` | `/report`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/coaches${`?${string}` | `#${string}` | ''}` | `/coaches${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/inventory${`?${string}` | `#${string}` | ''}` | `/inventory${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/membership${`?${string}` | `#${string}` | ''}` | `/membership${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/payment${`?${string}` | `#${string}` | ''}` | `/payment${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/plan${`?${string}` | `#${string}` | ''}` | `/plan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/report${`?${string}` | `#${string}` | ''}` | `/report${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coaches` | `/coaches`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/inventory` | `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/membership` | `/membership`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/payment` | `/payment`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/plan` | `/plan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/report` | `/report`; params?: Router.UnknownInputParams; };
    }
  }
}
